sec2/rails_asset_pipeline/class_mad_stylz/config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#index'

  get 'static_pages/contact'

  get 'static_pages/about'
end

sec2/rails_asset_pipeline/class_mad_stylz/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end

  def contact
  end

  def about
  end
end

sec2/rails_asset_pipeline/class_mad_stylz/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

sec2/rails_asset_pipeline/class_mad_stylz/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ClassMadStylz</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

sec2/rails_asset_pipeline/class_mad_stylz/app/views/static_pages/about.html.erb
<h1>THINGS I WRAP ABOUT</h1>

<p>Gross Stuff! Like pooin' ya pantS!</p>

<%= link_to 'Index', root_path %>
<%= link_to 'Contact', static_pages_contact_path %>

sec2/rails_asset_pipeline/class_mad_stylz/app/views/static_pages/contact.html.erb
<h1>Who want the real cool Brandon!?!?</h1>

<div>
  <p>These keys for me: <b><span id="place"></span></b></p>
</div>

<input type="text" id="take" placeholder="me key?"></input>

<br>
<br>

<%= link_to 'Index', root_path %>
<%= link_to 'About', static_pages_about_path %>

sec2/rails_asset_pipeline/class_mad_stylz/app/views/static_pages/index.html.erb
<h1>COOL BRANDON</h1>
<h3 id="subhead1">Being cool and wrappin! Yah!</h3>

<%= image_tag("boy_rap") %>

<%= link_to 'Contact', static_pages_contact_path %>
<%= link_to 'About', static_pages_about_path %>